---
###############################################################################
# Erlang installation

- name: Erlang | Installs dependencies | apt
  become: yes
  become_user: root
  loop: "{{ dependencies }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Erlang | Installs Erlang plugin | command
  command: "{{ asdf_bin }} plugin-add erlang"
  register: erlang_add
  failed_when: erlang_add.rc == 1

- name: Erlang | Installs Erlang versions | command
  command: "{{ asdf_bin }} install erlang {{ item }}"
  loop: "{{ erlang_versions }}"

- name: Erlang | Sets default Erlang version | command
  command: "{{ asdf_bin }} global erlang {{ erlang_versions[0] }}"
